# Config file for travis-ci.org
sudo: required
dist: trusty
language: php
php:
  - "nightly"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
branches:
  except:
    - release
matrix:
  allow_failures:
    - php: "nightly"
before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - ln -s `which nodejs` ~/bin/node && export PATH="~/bin/:$PATH"
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - yarn install
install: sh travis.sh
script:
  - cd _test && ./phpunit.phar --stderr --group plugin_prosemirror
  - cd ../lib/plugins/prosemirror
  - yarn test
  - yarn lint
before_deploy:
  - yarn build
  - rm -rf script _test _jstest node_modules .travis.yml webpack.config.js yarn.lock requirements.txt .gitignore package.json
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOYTOKEN
  target-branch: release
  local-dir: lib/plugins/prosemirror
  on:
    branch: master
    condition: $DOKUWIKI = master
    php: '7.2'
